#
# Perform a regular build on any branch except the main branch.

name: build

on:
    push:
        branches-ignore:
            - main

jobs:
    test-typescript:
        name: TypeScript Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5.0.0

            - name: Setup Node
              uses: actions/setup-node@v5.0.0
              with:
                  node-version: 24.7.0
                  cache: npm

            - name: Install Dependencies
              run: npm ci

            - name: Check Format
              run: npm run format:check

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run ci-test
