#
# Perform a regular build on any branch except the main branch.

name: build

on:
    push:
        branches-ignore:
            - main

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5.0.0

            - name: Setup Node
              uses: actions/setup-node@v5.0.0
              with:
                  node-version: 24.7.0
                  cache: npm

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run bundle

            - name: Test
              run: npm run ci-test

            - name: Generate version
              id: local-version
              uses: ./
              with:
                  ecosystem: javascript
                  major: 1
                  minor: 0

            - name: Print Version output
              run: echo "${{ steps.local-version.outputs.version }}"
