#
# Perform a regular build on any branch except the main branch.

name: build

on:
    push:
        branches-ignore:
            - main

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5.0.0

            - name: Setup Node
              uses: actions/setup-node@v5.0.0
              with:
                  node-version: 24.7.0
                  cache: npm

            - name: Generate version
              uses: .
              with:
                ecosystem: javascript
                major: 1
                minor: 0

            - name: Install Dependencies
              run: npm ci

            - name: Check Format
              run: npm run format:check

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run ci-test

            - name: Build
              run: npm run bundle
