#
# This workflow triggers checks for a PR and then a release when it is merged

name: release

on:
  push:
    branches: [main]

permissions:
  contents: write

env:
  PYTHON_VERSION: 3.13.7

jobs:
  version:
    uses: ./.github/workflows/version.yml

  build:
    runs-on: ubuntu-latest
    needs: version
    env:
      MRMAT_VERSION: ${{ needs.version.outputs.version }}
    steps:

    - name: Checkout out our code
      uses: actions/checkout@v4

    - name: Set up uv and Python
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Build
      run: uv build --wheel

  release:
    runs-on: ubuntu-latest
    needs:
    - version
    - build
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.version.outputs.version }}
        release_name: Release ${{ needs.version.outputs.version }}
        body: |
          Release ${{ needs.version.outputs.version }}
        draft: false
        prerelease: false