#
# This workflow triggers checks for a PR and then a release when it is merged

name: release

on:
    push:
        branches: [main]

permissions:
    contents: write

jobs:
    version:
        uses: ./
        with:
            ecosystem: javascript
            major: 1
            minor: 0

    build:
        runs-on: ubuntu-latest
        needs: version
        env:
            MRMAT_VERSION: ${{ needs.version.outputs.version }}
        steps:
            - name: Checkout
              uses: actions/checkout@v5.0.0

            - name: Setup Node
              uses: actions/setup-node@v5.0.0
              with:
                  node-version: 24.7.0
                  cache: npm

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run bundle

    release:
        runs-on: ubuntu-latest
        needs:
            - version
            - build
        steps:
            - name: Create Release
              id: create_release
              uses: actions/create-release@latest
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ needs.version.outputs.version }}
                  release_name: Release ${{ needs.version.outputs.version }}
                  body: |
                      Release ${{ needs.version.outputs.version }}
                  draft: false
                  prerelease: false
