#
# This workflow triggers checks for a PR and then a release when it is merged

name: release

on:
    push:
        branches: [main]

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5.0.0

            - name: Generate version
              id: local-version
              uses: ./
              with:
                  ecosystem: javascript
                  major: 1
                  minor: 0

            - name: Create Release
              id: create_release
              uses: actions/create-release@latest
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.local-version.outputs.version }}
                  release_name:
                      Release ${{ steps.local-version.outputs.version }}
                  body: |
                      Release ${{ steps.local-version.outputs.version }}
                  draft: false
                  prerelease: false
